### ISSUE TITLE
Issues in your week 2 submission

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad21-practical-2---android-activity-ngrayzin#2]
https://github.com/MAD11877/mad21-practical-2---android-activity-ngrayzin/blob/959cb2a4664942165909cb9c03f58a048d22973e/app/src/main/java/com/example/mad21_practical_2___android_activity_ngrayzin/MainActivity.java#L19-L23

something missing here

The challenge question not completed also

**Comment by ngrayzin** [comment]
i do the challenge liao and corrected the mistake
